[package]
name = "test_winit_with_octotablet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
octotablet = "0.1.0"
winit = "0.29.15"
windows ={version ="0.56.0", features=["Win32", "Win32_Graphics_Gdi"]}