[workspace]

[package]
name = "wintab_libloading"
version = "0.1.0"
edition = "2021"

[dependencies]

anyhow = "1.0.81"
libloading = "0.8.3"
winit = "0.29.15"
wintab_lite = {path="../../../wintab_lite"}

[dependencies.windows]
version="0.56.0"
features=[
    "Win32_Graphics_Gdi",
]
